#!/usr/bin/env python
"""Visualize painted LiDAR generated by the cloned PointPainting repo."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image


CLASS_NAMES = ("background", "bicycle/cyclist", "car", "person")
CLASS_COLORS = np.array(
    [
        [130, 130, 130],
        [55, 150, 75],
        [225, 70, 55],
        [65, 125, 225],
    ],
    dtype=np.uint8,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create projection and BEV plots for official painted lidar.")
    parser.add_argument("--image", required=True, type=Path)
    parser.add_argument("--painted", required=True, type=Path, help="Painted .npy with x,y,z,intensity,s0..s3.")
    parser.add_argument("--calib", required=True, type=Path, help="KITTI calibration txt.")
    parser.add_argument("--out-dir", required=True, type=Path)
    return parser.parse_args()


def read_calib(calib_path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    mats: dict[str, np.ndarray] = {}
    for line in calib_path.read_text().splitlines():
        if not line.strip():
            continue
        key, values = line.split(":", 1)
        vals = np.fromstring(values, sep=" ", dtype=np.float64)
        mats[key] = vals
    p2 = mats["P2"].reshape(3, 4)
    r0 = mats["R0_rect"].reshape(3, 3)
    tr = mats["Tr_velo_to_cam"].reshape(3, 4)
    return p2, r0, tr


def project(points_xyz: np.ndarray, p2: np.ndarray, r0: np.ndarray, tr: np.ndarray, image_size: tuple[int, int]):
    width, height = image_size
    points_h = np.concatenate([points_xyz, np.ones((points_xyz.shape[0], 1))], axis=1)
    cam = points_h @ tr.T
    rect = cam @ r0.T
    rect_h = np.concatenate([rect, np.ones((rect.shape[0], 1))], axis=1)
    img = rect_h @ p2.T
    depth = rect[:, 2]
    u = img[:, 0] / np.maximum(img[:, 2], 1e-6)
    v = img[:, 1] / np.maximum(img[:, 2], 1e-6)
    keep = (depth > 0) & (u >= 0) & (u < width) & (v >= 0) & (v < height)
    return keep, u[keep], v[keep]


def add_legend(ax: plt.Axes) -> None:
    handles = [
        plt.Line2D(
            [0],
            [0],
            marker="o",
            color="none",
            markerfacecolor=CLASS_COLORS[i] / 255.0,
            markersize=5,
            label=CLASS_NAMES[i],
        )
        for i in range(len(CLASS_NAMES))
    ]
    ax.legend(handles=handles, loc="lower right", fontsize=7, framealpha=0.78)


def save_projection(image: np.ndarray, u: np.ndarray, v: np.ndarray, labels: np.ndarray, out_path: Path) -> None:
    height, width = image.shape[:2]
    fig = plt.figure(figsize=(width / 120, height / 120), dpi=120)
    ax = fig.add_axes([0, 0, 1, 1])
    ax.imshow(image)
    ax.scatter(u, v, c=CLASS_COLORS[labels] / 255.0, s=2.2, linewidths=0, alpha=0.96)
    ax.axis("off")
    add_legend(ax)
    fig.savefig(out_path, dpi=180, bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)


def save_bev(points: np.ndarray, labels: np.ndarray, out_path: Path) -> None:
    x, y, z = points[:, 0], points[:, 1], points[:, 2]
    keep = (x > 0) & (x < 80) & (np.abs(y) < 40) & (z > -3) & (z < 3)
    fig, ax = plt.subplots(figsize=(8, 8), dpi=180)
    ax.scatter(y[keep], x[keep], c=CLASS_COLORS[labels[keep]] / 255.0, s=0.45, linewidths=0, alpha=0.9)
    ax.set_xlim(-40, 40)
    ax.set_ylim(0, 80)
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel("Lateral y (m)")
    ax.set_ylabel("Forward x (m)")
    ax.set_title("Official PointPainting painted LiDAR BEV")
    ax.grid(True, linewidth=0.3, alpha=0.35)
    add_legend(ax)
    fig.savefig(out_path, bbox_inches="tight", pad_inches=0.08)
    plt.close(fig)


def save_score_hist(scores: np.ndarray, out_path: Path) -> None:
    labels = scores.argmax(axis=1)
    counts = np.bincount(labels, minlength=len(CLASS_NAMES))
    fig, ax = plt.subplots(figsize=(6, 3.2), dpi=180)
    ax.bar(CLASS_NAMES, counts, color=CLASS_COLORS / 255.0)
    ax.set_ylabel("Painted points")
    ax.set_title("Point semantic labels after painting")
    ax.tick_params(axis="x", labelrotation=20)
    fig.tight_layout()
    fig.savefig(out_path, bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)


def save_panel(paths: dict[str, Path], out_path: Path) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(12, 7), dpi=180)
    items = [
        ("Camera", paths["camera"]),
        ("Official painted projection", paths["projection"]),
        ("Painted BEV", paths["bev"]),
        ("Painted label counts", paths["hist"]),
    ]
    for ax, (title, path) in zip(axes.ravel(), items):
        ax.imshow(Image.open(path).convert("RGB"))
        ax.set_title(title, fontsize=10)
        ax.axis("off")
    fig.tight_layout(pad=0.8)
    fig.savefig(out_path, bbox_inches="tight", pad_inches=0.04)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    image = np.asarray(Image.open(args.image).convert("RGB"))
    painted = np.load(args.painted)
    scores = painted[:, 4:8]
    labels = scores.argmax(axis=1)
    p2, r0, tr = read_calib(args.calib)
    keep, u, v = project(painted[:, :3], p2, r0, tr, (image.shape[1], image.shape[0]))

    camera_out = args.out_dir / "camera_raw.png"
    projection_out = args.out_dir / "official_pointpainting_projection.png"
    bev_out = args.out_dir / "official_painted_bev.png"
    hist_out = args.out_dir / "official_painted_label_counts.png"
    panel_out = args.out_dir / "official_pointpainting_panel.png"

    Image.fromarray(image).save(camera_out)
    save_projection(image, u, v, labels[keep], projection_out)
    save_bev(painted[:, :3], labels, bev_out)
    save_score_hist(scores, hist_out)
    save_panel(
        {"camera": camera_out, "projection": projection_out, "bev": bev_out, "hist": hist_out},
        panel_out,
    )

    counts = dict(zip(CLASS_NAMES, np.bincount(labels, minlength=len(CLASS_NAMES)).tolist()))
    (args.out_dir / "run_notes.md").write_text(
        "\n".join(
            [
                "# Official PointPainting Reproduction Notes",
                "",
                "## Result",
                "",
                "- Used the cloned `PointPainting/painting/painting.py` pipeline with `--seg-net 0`.",
                "- Semantic model: torchvision DeepLabV3 ResNet101 pretrained on COCO/VOC labels, which is the repo's `deeplabv3` branch.",
                f"- Painted lidar file: `{args.painted}`.",
                f"- Painted lidar shape: `{painted.shape}`. Columns are `x,y,z,intensity,s0,s1,s2,s3`.",
                f"- Projected painted points in image: `{int(keep.sum())}`.",
                f"- Label counts: `{counts}`.",
                "",
                "## Commands",
                "",
                "```bash",
                "cd PointPainting/painting",
                "/root/miniconda3/envs/motiondetection/bin/python painting.py \\",
                "  --seg-net 0 \\",
                "  --training-path ../detector/data/kitti/training \\",
                "  --save-path ../../outputs/pointpainting_official/painted_lidar \\",
                "  --sample-idx 000008",
                "",
                "cd ../..",
                "/root/miniconda3/envs/motiondetection/bin/python scripts/visualize_official_pointpainting.py \\",
                "  --image PointPainting/detector/data/kitti/training/image_2/000008.png \\",
                "  --painted outputs/pointpainting_official/painted_lidar/000008.npy \\",
                "  --calib PointPainting/detector/data/kitti/training/calib/000008.txt \\",
                "  --out-dir outputs/pointpainting_official",
                "```",
                "",
                "## Limitation",
                "",
                "The cloned repo's DeepLabV3+ branch requires `mmcv<=1.4.0`, but the current environment has `mmcv==2.1.0` for BEVFusion. To avoid breaking that environment, this run used the repo's torchvision DeepLabV3 branch. Detector inference still needs a trained `pointpillar_painted` checkpoint and OpenPCDet installation.",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print(f"Painted shape: {painted.shape}")
    print(f"Projected painted points: {int(keep.sum())}")
    print(f"Outputs written to: {args.out_dir}")


if __name__ == "__main__":
    main()
